### ISSUE TITLE
Incompatible with normal populate

### ISSUE THREAD

**Issue by sibelius** [alexmingoia/mongoose-populate-virtuals#8]
I'm getting an error, when I try to populate a field that is not a reference

``` js
const Product = new mongoose.Schema({
  user: {type: ObjectId, ref: 'User'}
});

const product = await Product.find().populate('user').exec();
```

Error:

``` js
TypeError: Invalid `path`. Must be either string or array
at Object.exports.get (app/node_modules/mpath/lib/index.js:49:11)
at Object.exports.getValue (app/node_modules/mongoose/lib/utils.js:624:16)
at app/node_modules/mongoose-populate-virtuals/index.js:591:26
at Array.forEach (native)
at assignVals (app/node_modules/mongoose-populate-virtuals/index.js:590:8)
at EventEmitter.<anonymous> (app/node_modules/mongoose-populate-virtuals/index.js:355:5)
at EventEmitter.<anonymous> (app/node_modules/mpromise/lib/promise.js:180:45)
at emitThree (events.js:110:13)
at EventEmitter.emit (events.js:188:7)
at Promise.safeEmit (app/node_modules/mpromise/lib/promise.js:83:21)
at Promise.fulfill (app/node_modules/mpromise/lib/promise.js:104:24)
at Promise.resolve (app/node_modules/mongoose/lib/promise.js:142:23)
at next (app/node_modules/mongoose-populate-virtuals/index.js:414:15)
at app/node_modules/kareem/index.js:177:19
at app/node_modules/kareem/index.js:109:16
at nextTickCallbackWith0Args (node.js:453:9)
```

**Comment by rturk** [comment]
+1

**Comment by alexmingoia** [comment]
Yes, this is intentional. Mongoose's behavior of overriding objectId fields with documents is terrible, as it introduces unnecessary type checks in application code. This plugin changes `.populate()` to populate virtual attributes. ObjectId attributes are left untouched.

**Comment by sibelius** [comment]
thanks for the explanation, mongoengine in python does the same.

sometimes it gets trick
